apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    app: nginx_app
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    command: ["sleep", "infinity"]

#then run: kubectl create -f pod.yaml
